cart/urls.py
from django.urls import path

from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail_view, name='cart_detail'),
    path('add/<int:product_id>/', views.add_to_cart_view, name='cart_add'),
    path('remove/<int:product_id>/', views.remove_cart_view, name='cart_remove')
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pages.urls')),
    path('accounts/', include('allauth.urls')),
    path('products/', include('products.urls')),
    path('cart/', include('cart.urls')),

    # Rosetta (i18n)
    path('rosetta/', include('rosetta.urls')),
]

pages/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.HomePageView.as_view(), name='home'),
    path('aboutus/', views.AboutUsView.as_view(), name='aboutus'),
]

products/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.ProductListView.as_view(), name='product_list'),
    path('<int:pk>/', views.ProductDetailView.as_view(), name='product_detail'),
    path('comment/<int:product_id>/', views.CommentCreateView.as_view(), name='comment_create'),
]

accounts/models.py
from django.db import models

from django.contrib.auth.models import AbstractUser

class CustomUser(AbstractUser):
    pass

cart/models.py
from django.db import models

# Create your models here.

products/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth import get_user_model
from django.utils.translation import gettext_lazy as _

class Product(models.Model):
    title = models.CharField(max_length=50, verbose_name=_('Title'))
    description = models.TextField(verbose_name=_('Description'))
    price = models.PositiveIntegerField(default=0, verbose_name=_('Price'))
    active = models.BooleanField(default=True)

    datetime_created = models.DateTimeField(auto_now_add=True, verbose_name=_('Create date'))
    datetime_modified = models.DateTimeField(auto_now=True, verbose_name=_('Update date'))

    def get_absolute_url(self):
        return reverse('product_detail', args=[self.pk])

class ActiveCommentManager(models.Manager):
    def get_queryset(self):
        return super(ActiveCommentManager, self).get_queryset().filter(active=True)

class Comment(models.Model):
    PRODUCT_STARS = [
        ('1', _('Very Bad')),
        ('2', _('Bad')),
        ('3', _('Normal')),
        ('4', _('Good')),
        ('5', _('Perfect')),
    ]
    author = models.ForeignKey(get_user_model(),
                               on_delete=models.CASCADE, related_name='comments', verbose_name=_('Comment author'))
    body = models.TextField(verbose_name=_('Comment Text'), max_length=200)
    stars = models.CharField(max_length=10, choices=PRODUCT_STARS, verbose_name=_('What is your score?'))
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='comments', verbose_name=_('Product'))

    datetime_created = models.DateTimeField(auto_now_add=True, verbose_name=_('Create date'))
    datetime_modified = models.DateTimeField(auto_now=True, verbose_name=_('Update date'))
    active = models.BooleanField(default=True, verbose_name=_('Active'))

    # manager
    objects = models.Manager()
    active_comment_manager = ActiveCommentManager()

    def get_absolute_url(self):
        return reverse('product_detail', args=[self.product.id])

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.auth import get_user_model

class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = get_user_model()
        fields = ('email', 'username', )

class CustomUserChangForm(UserChangeForm):
    class Meta:
        model = get_user_model()
        fields = ('email', 'username', )

cart/forms.py
from django import forms

class AddToCartProductForm(forms.Form):
    QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 31)]

    quantity = forms.TypedChoiceField(choices=QUANTITY_CHOICES, coerce=int)

    inplace = forms.BooleanField(required=False, widget=forms.HiddenInput)

products/forms.py
from django import forms
from .models import Comment

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['body', 'stars']

cart/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views.decorators.http import require_POST

from products.models import Product
from .forms import AddToCartProductForm
from .cart import Cart

def cart_detail_view(request):
    cart = Cart(request)

    for item in cart:
        item['product_update_quantity_form'] = AddToCartProductForm(initial={
            'quantity': item['quantity'],
            'inplace': True,
        })

    return render(request, 'cart/cart_details.html', {
        'cart': cart,
    })

@require_POST
def add_to_cart_view(request, product_id):
    cart = Cart(request)

    product = get_object_or_404(Product, id=product_id)
    form = AddToCartProductForm(request.POST)

    if form.is_valid():
        cleaned_data = form.cleaned_data
        quantity = cleaned_data['quantity']
        cart.add(product, quantity, replace_current_quantity=cleaned_data['inplace'])

        return redirect('cart:cart_detail')


def remove_cart_view(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)

    return redirect('cart:cart_detail')

pages/views.py
from django.views.generic import TemplateView

class HomePageView(TemplateView):
    template_name = 'home.html'

class AboutUsView(TemplateView):
    template_name = 'pages/aboutus.html'

products/views.py
from django.views import generic
from django.shortcuts import get_object_or_404
from django.contrib import messages
from django.utils.translation import gettext as _

from .models import Product, Comment
from .forms import CommentForm

class ProductListView(generic.ListView):
    queryset = Product.objects.filter(active=True)
    template_name = 'products/product_list.html'
    context_object_name = 'products'

class ProductDetailView(generic.DetailView):
    model = Product
    template_name = 'products/product_detail.html'
    context_object_name = 'product'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['comment_form'] = CommentForm()
        return context

class CommentCreateView(generic.CreateView):
    model = Comment
    form_class = CommentForm

    def form_valid(self, form):
        obj = form.save(commit=False)
        obj.author = self.request.user

        product_id = int(self.kwargs['product_id'])
        product = get_object_or_404(Product, id=product_id)
        obj.product = product

        messages.success(self.request, _('Comment successfully added'))
        return super().form_valid(form)

cart/templates/cart/cart_details.html
{% extends '_base.html' %}
{% load i18n %}
{% block page_title %}
    {% trans 'Cart' %}
{% endblock %}

{% block content %}
    <!-- Main Wrapper Start -->
    <div class="wrapper">
        <!-- Breadcrumb area Start -->
        <div class="breadcrumb-area bg-color ptb--90" data-bg-color="#f6f6f6">
            <div class="container">
                <div class="row">
                    <div class="col-12">
                        <div class="d-flex justify-content-between align-items-center flex-sm-row flex-column">
                            <h1 class="page-title">{% trans 'Shpping cart' %}</h1>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Breadcrumb area End -->

        <!-- Main Content Wrapper Start -->
        <div class="main-content-wrapper">
            <div class="page-content-inner ptb--80">
                <div class="container">
                    <div class="row">
                        <div class="col-lg-8 mb-md--50">
                                <div class="row no-gutters">
                                    <div class="col-12">
                                        <div class="table-content table-responsive">
                                            <table class="table text-center">
                                                <thead>
                                                <tr>
                                                    <th>{% trans 'Remove product' %}</th>
                                                    <th>{% trans 'Product picture' %}</th>
                                                    <th>{% trans 'Product title' %}</th>
                                                    <th>{% trans 'Product Price' %}</th>
                                                    <th>{% trans 'Quantity' %}</th>
                                                    <th>{% trans 'Total price' %}</th>
                                                </tr>
                                                </thead>
                                                <tbody>
                                                {% for item in cart %}
                                                    <tr>
                                                        <td class="product-remove text-left"><a
                                                                href="{% url 'cart:cart_remove' item.product_obj.id %}"><i
                                                                class="flaticon flaticon-cross"></i></a></td>
                                                        <td class="product-thumbnail text-left">
                                                            <img src="assets/img/products/prod-10-70x88.jpg">
                                                        </td>
                                                        <td class="product-name">
                                                            <h3>
                                                                <a href="{{ item.product_obj.get_absolute_url }}">{{ item.product_obj.title }}</a>
                                                            </h3>
                                                        </td>
                                                        <td class="product-price">
                                                            <span class="product-price-wrapper">
                                                                <span class="money">{{ item.product_obj.price }} {% trans '$' %}</span>
                                                            </span>
                                                        </td>
                                                        <td class="product-quantity">
                                                            <form class="d-flex" action="{% url 'cart:cart_add' item.product_obj.id %}" method="POST">
                                                                {% csrf_token %}
                                                                <div class="quantity">
                                                                    <input type="number" class="quantity-input"
                                                                           name="quantity"
                                                                           id="qty-1" value="{{ item.quantity }}"
                                                                           min="1">
                                                                </div>
                                                                {{ item.product_update_quantity_form.inplace }}
                                                                <button type="submit" class="small"><i class="fa fa-refresh"></i></button>
                                                            </form>
                                                        </td>
                                                        <td class="product-total-price">
                                                            <span class="product-price-wrapper">
                                                                <span class="money">{{ item.total_price }} {% trans '$' %}</span>
                                                            </span>
                                                        </td>
                                                    </tr>
                                                {% endfor %}
                                                </tbody>
                                            </table>
                                        </div>
                                    </div>
                                </div>
                                <div class="row no-gutters border-top pt--20 mt--20">
                                    <div class="col-sm-6 text-sm-right">
                                        <button type="submit" class="cart-form__btn">{% trans 'Clear cart' %}</button>
                                    </div>
                                </div>
                        </div>
                        <div class="col-lg-4">
                            <div class="cart-collaterals">
                                <div class="cart-totals">
{#                                    <h5 class="font-size-14 font-bold mb--15">مجموع</h5>#}
{#                                    <div class="cart-calculator">#}
{#                                        <div class="cart-calculator__item">#}
{#                                            <div class="cart-calculator__item--head">#}
{#                                                <span>مجموع</span>#}
{#                                            </div>#}
{#                                            <div class="cart-calculator__item--value">#}
{#                                                <span>۳۴۶,۰۰۰ تومان</span>#}
{#                                            </div>#}
{#                                        </div>#}
                                        <div class="cart-calculator__item order-total">
                                            <div class="cart-calculator__item--head">
                                                <span>{% trans 'Total price' %}</span>
                                            </div>
                                            <div class="cart-calculator__item--value">
                                                <span class="product-price-wrapper">
                                                    <span class="money">{{ cart.get_total_price }} {% trans '$' %}</span>
                                                </span>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <a href="checkout.html"
                                   class="btn btn-fullwidth btn-bg-red btn-color-white btn-hover-2">
                                    {% trans 'Confirm' %}
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Main Content Wrapper Start -->

    <!-- Main Wrapper End -->

{% endblock %}

pages/templates/pages/aboutus.html
<h1>About Us</h1>

products/templates/products/product_detail.html
{% extends '_base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% load comment_tags %}
{% load i18n %}

{% block page_title %} {% trans 'Products Detail' %} {% endblock %}

{% block content %}
    <div class="main-content-wrapper">
        <div class="page-content-inner ptb--80">
            <div class="container">
                <div class="row no-gutters mb--80">
                    <div class="col-12 col-sm-4 product-main-image d-flex align-content-center">
                        <img class="m-auto" style="max-height: 400px;"
                             src="https://dkstatics-public.digikala.com/digikala-products/8f34ee9823202d09ee97deb9b1c8e3300a9a24d8_1643265727.jpg?x-oss-process=image/resize,w_1600/quality,q_80"
                             alt="">
                    </div>
                    <div class="col-12 col-sm-8 product-main-details mt-md--50">
                        <div class="product-summary pl-lg--30 pl-md--0 text-right p-4">
                            <h3 class="product-title mb--20">{{ product.title }}</h3>
                            <p class="product-short-description mb--20">
                                {{ product.description }}
                            </p>
                            <div class="my-5 py-5 product-price-wrapper mb--25">
                                <span class="money text-success">۱۴۸,۰۰۰ {% trans '$' %}</span>
                                <span class="price-separator">-</span>
                                <span class="money old-price text-danger">{{ product.price }} {% trans '$' %}</span>
                            </div>
                            <div class="product-action d-flex align-items-sm-center align-content-center mb--30">
                                <form action="{% url 'cart:cart_add' product.id %}" method="post">
                                    {% csrf_token %}
                                    <div class="quantity-wrapper d-flex justify-content-start">
                                        <div class="quantity">
                                            <input type="number" class="quantity-input" name="quantity" id="qty" value="1"
                                                   min="1" max="30">
                                        </div>
                                    </div>
                                    <button type="submit" class="btn btn-small btn-bg-red btn-color-white btn-hover-2">
                                        {% trans 'Add to Cart' %}
                                    </button>
                                </form>
                            </div>
                            <div class="product-footer-meta mt-5 pt-5">
                                <p><span class="m-0">{% trans 'Categories' %}:</span>
                                    <a href="shop.html">لباس</a>,
                                    <a href="shop.html">تابستانی</a>,
                                    <a href="shop.html">گرم</a>,
                                    <a href="shop.html">زنانه</a>
                                </p>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row justify-content-center">
                    <div class="col-12">
                        <div class="product-data-tab tab-style-3">
                            <div class="nav nav-tabs product-data-tab__head" id="product-tab" role="tablist">
                                <a class="m-0 product-data-tab__link nav-link active" id="nav-description-tab"
                                   data-toggle="tab" href="#nav-description" role="tab" aria-selected="true">
                                    <span>{% trans 'Product description' %}</span>
                                </a>
                                <a class="m-0 product-data-tab__link nav-link" id="nav-info-tab" data-toggle="tab"
                                   href="#nav-info" role="tab" aria-selected="true">
                                    <span>{% trans 'Features' %}</span>
                                </a>
                                <a class="m-0 product-data-tab__link nav-link" id="nav-reviews-tab" data-toggle="tab"
                                   href="#nav-reviews" role="tab" aria-selected="true">
                                    <span>{% trans 'Comments' %} ({{ product.comments.all|only_active_comments|length }})</span>
                                </a>
                            </div>
                            <div class="tab-content product-data-tab__content" id="product-tabContent">
                                <div class="tab-pane fade show active" id="nav-description" role="tabpanel"
                                     aria-labelledby="nav-description-tab">
                                    <div class="product-description text-justify">
                                        <p>{{ product.description }}</p>
                                    </div>
                                </div>
                                <div class="tab-pane text-right" id="nav-info" role="tabpanel"
                                     aria-labelledby="nav-info-tab">
                                    <div class="table-content table-responsive">
                                        <table class="table shop_attributes">
                                            <tbody>
                                            <tr>
                                                <th>وزن</th>
                                                <td>۴۳۰ گرم</td>
                                            </tr>
                                            <tr>
                                                <th>سایز</th>
                                                <td>XL</td>
                                            </tr>
                                            <tr>
                                                <th>رنگ</th>
                                                <td>
                                                    <a href="shop-sidebar.html">مشکی</a>,
                                                    <a href="shop-sidebar.html">سبز</a>,
                                                    <a href="shop-sidebar.html">قرمز</a>,
                                                    <a href="shop-sidebar.html">نارنجی</a>,
                                                </td>
                                            </tr>
                                            </tbody>
                                        </table>
                                    </div>
                                </div>
                                <div class="tab-pane fade" id="nav-reviews" role="tabpanel"
                                     aria-labelledby="nav-reviews-tab">
                                    <div class="product-reviews">
                                        <h3 class="review__title">{{ product.comments.all|only_active_comments|length }} {% trans 'Comments for' %} {{ product.title }}</h3>
                                        <ul class="review__list">
                                            <li class="review__item">
                                                {% for comment in product.comments.all %}
                                                    <div class="review__container">
                                                        <div class="review__text">
                                                            <div class="d-flex flex-sm-row flex-row">
                                                                <img src="{% static 'img/others/comment-1.jpg' %}"
                                                                     alt="Review Avatar" class="review__avatar p-3">
                                                                <div>
                                                                    <div class="review__meta">
                                                                        <strong class="review__author px-4">{{ comment.author }}</strong>
                                                                        <span class="review__published-date">{{ comment.datetime_created }}</span>
                                                                        <span class="review__dash">-</span>
                                                                    </div>
                                                                    <div class="product-rating">
                                                                        <div class="m-0 star-rating star-five">
                                                                            <span>{% trans 'Rated' %} <strong
                                                                                    class="rating">{{ comment.stars }}</strong>{% trans 'out of 5' %}</span>
                                                                        </div>
                                                                    </div>
                                                                </div>
                                                            </div>
                                                            <p class="review__description text-right px-4 pt-2">
                                                                {{ comment.body }}
                                                            </p>
                                                        </div>
                                                    </div>
                                                {% endfor %}
                                            </li>
                                        </ul>
                                        <div class="review-form-wrapper">
                                            <div class="row">
                                                <div class="border-top py-5 w-100"></div>
                                                <div class="col-lg-8 m-auto">
                                                    {% if user.is_authenticated %}
                                                        <span class="reply-title pull-right">{% trans 'Write your comment' %}</span>
                                                    <br>
                                                    <form action="{% url 'comment_create' product.id %}" method="post"
                                                          class="form text-right">
                                                        {% csrf_token %}
                                                        {{ comment_form|crispy }}
                                                        <div class="col-12">
                                                            <input type="submit" value="{% trans 'Send' %}"
                                                                   class="btn-submit">
                                                        </div>
                                                    </form>
                                                    {% else %}
                                                        <p>{% trans 'Please Login in order to write your comment.' %}</p>
                                                    {% endif %}
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/home.html
{% extends '_base.html' %}

{% block page_title %}
    Home Page
{% endblock %}

{% block content %}
    <h1>Home</h1>
{% endblock %}